[package]
name = "ergosphere"
version = "0.5.0"
edition = "2024"
license = "GPL-3.0-only"
description = "A reactive, event-driven push replication daemon for Pi-hole v6 replica setups"
readme = "README.md"
repository = "https://github.com/nikhil-prabhu/ergosphere"
keywords = ["pihole", "dns", "replication", "sync", "daemon"]
categories = ["command-line-utilities", "network-programming"]
authors = ["Nikhil Prabhu <nikhilprabhu98@gmail.com>"]

[package.metadata.deb]
name = "ergosphere"
license-file = ["LICENSE", "0"]
extended-description = """\
ergosphere is a high-performance, real-time synchronization daemon \
designed to bridge adlists, domains, and configuration states seamlessly  \
across multiple Pi-hole v6 deployments.\
"""
section = "utility"
priority = "optional"
assets = [
    ["target/release/ergosphere", "/usr/bin/ergosphere", "755"],
    ["LICENSE", "usr/share/doc/ergosphere/LICENSE"],
    ["README.md", "usr/share/doc/ergosphere/README"]
]
maintainer-scripts = "dist/debian/"
systemd-units = { unit-name = "ergosphere", unit-scripts = "dist/systemd", enable = true }

[package.metadata.generate-rpm]
name = "ergosphere"
license = "GPL-3.0-only"
assets = [
    { source = "target/release/ergosphere", dest = "/usr/bin/ergosphere", mode = "755" },
    { source = "dist/systemd/ergosphere.service", dest = "/lib/systemd/system/ergosphere.service", mode = "644" },
    { source = "LICENSE", dest = "/usr/share/doc/ergosphere/LICENSE", doc = true },
    { source = "README.md", dest = "/usr/share/doc/ergosphere/README", doc = true }
]

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
bytes = { version = "1.11.1", features = ["serde"] }
config = { version = "0.15.23", features = ["toml"] }
dirs = "6.0.0"
notify = "8.2.0"
reqwest = { version = "0.13.3", features = ["json", "cookies", "multipart", "stream", "query"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
smart-default = "0.7.1"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt", "local-time"] }
url = "2.5.8"
clap = { version = "4.6.1", features = ["derive", "env"] }
toml = "1.1.2"
tracing-core = "0.1.36"
anyhow = "1.0.102"
tracing-error = "0.2.1"
notify-debouncer-full = "0.7.0"
sha2 = "0.11.0"
chrono-tz = "0.10.4"
chrono = "0.4.45"
