[package]
name = "ergosphere"
version = "0.2.0"
edition = "2024"
license = "GPL-3.0-only"
description = "A reactive, event-driven push replication daemon for Pi-hole v6 replica setups"
readme = "README.md"
repository = "https://github.com/nikhil-prabhu/ergosphere"
keywords = ["pihole", "dns", "replication", "sync", "daemon"]
categories = ["command-line-utilities", "network-programming"]

[dependencies]
bytes = { version = "1.11.1", features = ["serde"] }
config = { version = "0.15.23", features = ["toml"] }
dirs = "6.0.0"
notify = "8.2.0"
reqwest = { version = "0.13.3", features = ["json", "cookies", "multipart", "stream", "query"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
smart-default = "0.7.1"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt", "local-time"] }
url = "2.5.8"
futures-util = "0.3.32"
